### ISSUE TITLE
Vector operations relies on dynamic memory allocation

### ISSUE THREAD

**Issue by nwhean** [nwhean/42_core_minirt#1]
Have a look at the code below:

https://github.com/nwhean/42_core_minirt/blob/ffcfe8651fa7a4e9df5080408129a99e35b8dd1f/src/ft_vec_mul.c#L29-L44

You'll notice that whenever a vector operation returns another vector, a new vector is returned, since `ft_vec_new` is called. This means that the input vectors, as well as the newly returned vector, needs to be manually freed. In order to simplify the free operations, I've introduced a `ft_vec_del_many` function.

The alternative to this is to have a `out` argument for all such operations, for example, `t_vec	*ft_vec_mul_elem(t_vec *a, t_vec *b, t_vec *out)` so that the output will be written to a particular output vector if `out` is not NULL. But as you can imagine, the code becomes uglier.

Another altenative is to have a `inplace` argument for all such operations,  for example, `t_vec	*ft_vec_mul_elem(t_vec *a, t_vec *b, int inplace)` such that if `inplace` is `1`, the output will be written to the first input vector instead, i.e. `a` in this case. Again, you can imagine that the code becomes uglier again.

My personal preference is to maintain the code as is, and the user of the code will need to remember to properly free the vectors. What do you think?

**Comment by nwhean** [comment]
Another alternative is that the operations are always in-place, and if we need to retain the original vector, we should make a copy of it. Both the code and interface remains relatively clean.

Have a look at this:
https://www.gnu.org/software/gsl/doc/html/vectors.html?highlight=matrix%20multiplication#vector-operations

**Comment by HQLoke** [comment]
I agree with the freeing outside the vector operation function. I've read through all your vector codes, its pretty clean and modular. But I think most of the time we are just going to use the ft_vec3_new isn't it? On the other hand, it's convenient having a n-size ft_vec_new.

**Comment by nwhean** [comment]
What do you mean by "freeing the outside vector"?  Do you mean if we have a function `ft_vec(t_vec *a, t_vec *b)`, it should assign the result to the original vector `a` instead, i.e. `a = a + b`?

Actually, we may likely be dealing with 4D vector instead. There are benefits of representing 3D object in 4D space, since it makes the math simplier. Please look into affine transformation. If that's the case, then I'll probably add `ft_vec4_new` function, or replace the `ft_vec3_new`.

**Comment by HQLoke** [comment]
I agree with your statement 'user of the code will need to remember to properly free the vectors'.
I thought about the a = a + b and assign the result to a, but I think its best to assign values manually to prevent tempering the original vector values.

**Comment by nwhean** [comment]
I actually prefer the `a = a + b` because most of the time, we don't need to original `a` anymore. 

Have a look at an example code where new matrix is return after every operation:

https://github.com/nwhean/42_core_minirt/blob/3669c8383857ece3bb89db706af1697e02f9c2aa/test/test_ft_mat_op.c#L74-L97

In the example above, you have an explosion of dangling matrices that you have to subsequent delete, just from doing some simple calculation. It's one of the issues I noticed from my fdf project actually, but it's not too bad that requires my immediate attention back then.

Yeah, so I'm making a case for `a = a + b`. What do you think?

**Comment by nwhean** [comment]
I've pushed a branch called inplace, where all the matrix and vector operations are done in-place. I've also updated the test files, and for the same `test_affine_inverse`, you can see the the code is shorter, without an explosion of variables: 

https://github.com/nwhean/42_core_minirt/blob/dbc7cbfc27e575c80271dd30a2fd43cde450e7bd/test/test_ft_mat_op.c#L68-L93

**Comment by nwhean** [comment]
Decided that linear algebra operation should be done in-place.
