### ISSUE TITLE
test_ft_atof contains failed test

### ISSUE THREAD

**Issue by nwhean** [nwhean/42_core_minirt#4]
There are two test cases that failed:
https://github.com/nwhean/42_core_minirt/blob/4daabf14da385e9c6ce3da4adc5080178e93a0ba/test/utils/test_ft_atof.c#L26-L27

**Comment by HQLoke** [comment]
I don't understand. The output seem to be the same. Could you shine some more light on this problem?

**Comment by nwhean** [comment]
When you are in the test  folder, running `make ft_atof` prints out this output:

> ft_atof: Error for input -3.14159265359
>    atof output = -3.1415926535900001e+00
> ft_atof output = -3.1415926000000001e+00
> 
> ft_atof: Error for input 3.14159265359
>    atof output = 3.1415926535900001e+00
> ft_atof output = 3.1415926000000001e+00

You can se ethat they are only the same up to 3.1415926, and not after that.

**Comment by HQLoke** [comment]
I changed ft_atoi to ft_atol, seems to solve the problem already.

**Comment by nwhean** [comment]
I've added 3 test cases that would cause failure based on your current code.

https://github.com/nwhean/42_core_minirt/blob/24bfa5f409dff61b71c456f7f4c54715b45f79a6/test/utils/test_ft_atof.c#L34-L36

I think reliance on ft_atoi or ft_tol is not the right approach due to integer overflow issue.

**Comment by HQLoke** [comment]
I've created another version of ft_atof, removed atoi and atol, only using ft_isdigit and pow from math.h. Seems to pass the test cases for now. I have not simplified it for norminette yet.

**Comment by nwhean** [comment]
Resolved in commit cb6abaee3d191ec45a63200bd8db098ded00fc5e.
